/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessibilityWidgetSettingsCard: typeof import('./components/AccessibilityWidgetSettingsCard.vue')['default']
    CacheSettingsCard: typeof import('./components/CacheSettingsCard.vue')['default']
    CookieBannerSettingsCard: typeof import('./components/CookieBannerSettingsCard.vue')['default']
    DocumentEmbed: typeof import('./components/DocumentEmbed.vue')['default']
    PolicySettingsCard: typeof import('./components/PolicySettingsCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
